version: '2'

services:
  # =================================== Web ===================================
  web:
    image: lappis/web:latest
    build:
      context: .
      dockerfile: ./docker/web/web.Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8000
      - ALLOWED_HOSTS=localhost
      - PREFIX_URL=
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=webdb
      - SOCIAL_AUTH_GITHUB_KEY=<SET YOUR KEY VALUE HERE>
      - SOCIAL_AUTH_GITHUB_SECRET=<SET YOUR GITHUB SECRET HERE>
    volumes:
      - ./django_social_auth_app:/web/django_social_auth_app
    ports:
      - 8000:8000
    depends_on:
      - webdb

  webdb:
    image: postgres:10.5
    restart: unless-stopped
    volumes:
      - web_db:/var/lib/postgresql/data

volumes:
  web_db:
