# Generated by Django 2.2.4 on 2019-08-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playedHours',
        ),
    ]
